apiVersion: v1
kind: Service
metadata:
  name: bootcamp2-html
  namespace: prod
spec:
  selector:
    app: bootcamp2-html
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30101
    protocol: TCP
